using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataTier
{
    public class AllReportData
    {
        public int ID;
        public int NextPortID;
        public string Agency = "";
        public string VesOperator = "";
        public string VesVoyID = "";
        public string BLNumber = "";
        public string AgencyID = "";
        public int AgentID;
        public string POLID = "";
        public string VesVoy = "";
        public string ETD = "";
        public string NextPort = "";
        public string POL = "";
        public string TerminalName = "";
        public string NextPortETA = "";
        public string DestinationAgentID = "";
        public string DestinationAgent = "";
        public string Operator = "";
        public string OperatorID = "";
        public string BLID = "";
        public string VesselName = "";
        public string VoyageNo = "";
        public string ETA = "";
        public string VesselOperator = "";
        public string PODAgent = "";
        public string CntrNo = "";
        public string Size = "";
        public string BLNUMBER = "";
        public string ServiceType = "";
        public string TSPORT = "";
        public string POD = "";
        public string FPOD = "";
        public string Shipper = "";
        public string PickUpDate = "";
        public string GrsWt = "";
        public string SNo = "";
        public string NoofShipment = "";
        public string NoofCntr20 = "";
        public string NoofCntr40 = "";
        public string RevenuAmt = "";
        public string CostAmt = "";
        public string ProfitAmt = "";
        public string RRID = "";
        public string RRNo = "";
        public string SlotOperator = "";
        public string Size20 = "";
        public string Size40 = "";
        public string SizeRF40 = "";
        public string SizeOT40 = "";
        public string LeasTerms = "";
        public string OFT = "";
        public string BAF = "";
        public string BAFCURR = "";
        public string MISC = "";
        public string MISCCCURR = "";
        public string HLDTPT = "";
        public string DESTTHC = "";
        public string DESTTHCCURR = "";
        public string LOADTHC = "";
        public string LOADTHCCURR = "";
        public string BookingNo = "";
        public string SlotAmt = "";
        public string DESPORTTHC = "";
        public string LOADPORTTHC = "";
        public string MISCCOST = "";
        public string LOGCOST = "";
        public string AgentAddress = "";
        public string BLVesVoy = "";
        public string LoadTerminal = "";
        public string SURCHARGES = "";
        public string SURCHARGESCURR = "";
        public string SlotCURR = "";
        public string TSCOST = "";
        public string TSCOSTCURR = "";
        public string EXCOMM = "";
        public string EXCOMMCURR = "";
        public string ICOMM = "";
        public string ICOMMCURR = "";
        public string TSCOMM = "";
        public string TSCOMMCURR = "";
        public string LOADPHC = "";
        public string LOADPHCCURR = "";
        public string DESTPHC = "";
        public string DESTPHCCURR = "";
        public string MISCCOSTCURR = "";
        public string COSTAmt = "";
        public string OFTCURR = "";
        public string TypeSize = "";
        public string Commodity = "";
        public string ETDDate = "";
        public string ChargeCode = "";
        public string ManifRate = "";
        public string ShipperAddress = "";
        public string Consignee = "";
        public string ConsigneeAddress = "";
        public string Notify1 = "";
        public string Notify1Address = "";
        public string MarkNo = "";
        public string NoOfPkg = "";
        public string CargoDes = "";
        public string Seal = "";
        public string FreightPayment = "";
        public string CBM = "";
        public string CntrDetails = "";
        public string FRT = "";
        public string ECRS = "";
        public string ChkFlag = "";
        public string Items;
        public string TSPORTID = "";
        public string Total = "";
        public string FromDate = "";
        public string ToDate = "";
        public string SlotOperatorID = "";
    }

    

}
