using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataTier
{
   public class MyCustomerContract
    {
        public int ID;
        public int CustomerID;
        public int PrincipalID;
        public string ContractNo;
        public string ContractDate;
        public int SalesPersonID;
        public string ValidTill;
        public int OriginID;
        public int LoadPortID;
        public int DischargePortID;
        public int DestinationID;
        public int RouteID;
        public int DeliveryTermsID;
        public string Remarks;
        public int Status;
        public string UserName;
        public string SessionFinYear;
        public string CCNo;
        public string CustomerName;
        public string Principal;
        public string POL;
        public string POD;
        public string FPOD;
        public string StatusV;
        public int FreeDaysOriginType;
        public string FreeDaysOrigin;
        public int FreeDaysDestinationType;
        public string FreeDaysDestination;
        public int DamageSchemeType;
        public string DamageScheme;
        public int SecDepositType;
        public string SecDeposit;
        public int BOLReqType;
        public string BOLReq;
        public string Itemsv;
        public int CID;
        public int CCID;
        public int ContainerTypeID;
        public string Nos;
        public int CargoTypeID;
        public decimal OceanAmount;
        public int OceanCurrencyID;
        public decimal SlotAmount;
        public int SlotCurrencyID;
        public int POLStdID;
        public string POLAmount;
        public int POLCurrencyID;
        public int PODStdID;
        public int PODCurrencyID;
        public decimal PODAmount;
        public int RRID;
        public string RequestNo;
        public string ItemsAttach;
        public int AID;
        public string AttachFile;
        public string AttachName;
        public string Reason;
        public string CustomerN;
        public string PrincipalN;
        public int CancelReasonID;
        public int RejectReasonID;
        public string RejectReason;
        public string CancelReasonValue;
        public string RejectReasonValue;
        public string ValidStatus = "";
        public int ValidStatusID;
        public string ContractDateTill = "";
        public string ContractDateV = "";
        public int OfficeLocation;
        public int OpenCount;
        public string TextValues = "";
        public string PageName = "";
        public string UserID = "";
        public int OfficeLocID;
    }
}
