using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace DataTier
{
    public class MyEnquiry
    {
        public int ID = 0;

        public string PortName = "";
        public string AgencyID = "";
        public string PrincibalID = "";
        public string AgencyName = "";
        public string CntrType = "";
        public string CntrTypes = "";
        public string CntrTypeID = "";
        public string Nos = "";
        public string PerAmount = "";
        public string TotalAmount = "";
        public string Currency = "";
        public string CurrencyID = "";
        public string ManifestPerAmount = "";
        public string ManifestTotalAmount = "";
        public string CommPerAmount = "";
        public string CommTotal = "";
        public string Commodity = "";
        public string CommodityID = "";
        public string UOM = "";
        public string PaymentTerms = "";
        public string PaymentTermID = "";
        public string CostAmount = "";
        public string TotalCostAmount = "";
        public string ChargeCode = "";
        public string Amount = "";
        public string AlertMegId = "";
        public string AlertMessage = "";

        public string ShipperID = "";
        public string HSCode = "";
        public string CargoWeight = "";
        public string CargoID = "";
        public string DeliveryTermsID = "";
        public string RouteID = "";
        public string DestinationID = "";
        public string DischargeID = "";
        public string DischargePortID = "";
        public string LoadPortID = "";
        public string OriginID = "";
        public string SalesPersonID = "";
        public string NominationID = "";
        public string ValidTillDate = "";
        public string EnquiryStatusID = "";
        public string BookingCommissionID = "";
        public string EnquirySourceID = "";
        public string EnquiryDate = "";
        public string EnquiryDateto = "";
        public string EnquiryNo = "";
        public string ShipperChk = "";
        public string BkgPartyChk = "";
        public string CustomerID = "";

        public string VesselID = "";
        public string VoyagID = "";
        public string POLTerminalID = "";
        public string TranshipmentPortID = "";
        public string ItemsCntr = "";
        public string ItemsHarz = "";
        public string ItemsOutGaugeCargo = "";
        public string ItemsReeferGrid = "";
        public string ItemShimpmentPOL = "";
        public string ItemShimpmentPOD = "";
        public string ItemFreightRate = "";
        public string ItemSlotRate = "";
        public string ItemAttach = "";
        public string ItemRevenueCostRate = "";
        public string ExRate = "";
        public string CompnayName = "";
        public string Branch = "";
        public string POD = "";
        public string FPOD = "";
        public string BasicID = "";
        public string ChargeCodeID = "";
        public int HazarOpt = 1;
        public string HazarClass = "";
        public string HazarMCONo = "";
        public string Height = "";
        public string Width = "";
        public string Length = "";
        public string OutGaugeOption = "";
        public string Reffer = "";
        public string Temperature = "";
        public string Ventilation = "";
        public string Humidity = "";
        public string Amount1 = "";
        public string Amount2 = "";
        public string Amount3 = "";
        public int ChargeOPT = 0;
        public int ReeferOpt = 0;
        public int OOGOpt = 0;
        public string SessionFinYear = "";
        public string AgentCode = "";
        public string PaymentTermsID = "";
        public int FreeDayOrigin = 0;
        public int FreeDayDestination = 0;

        public string NumberOfDays = "";
        public string NumberOfDaysDestin = "";
        public int SecurityDeposit = 0;
        public string txtSecurityDeposit = "";
        public int BOLRequirement = 0;
        public string txtBOLRequirement = "";
        public int DamageScheme = 0;
        public string txtDamageScheme = "";
        public int PayTermsID = 0;
        public string BookingNo;
        public string ItemFreightBrackup = "";
        public string Type = "";
        public string PrincipalID = "";
        public string RequestNo = "";
        public string ContractNo = "";
        public string LineContractID = "";
        public string CustomerContractID = "";

        public int PODAgentID = 0;
        public int FPODAgentID = 0;
        public string TSAgentID = "";
        public string TSTwoAgentID = "";
        public string SlotOperatorID = "";
        public int OwnershipID = 0;
        public int FixedID = 0;
        public string TSVesselID = "";
        public string TSVoyageID = "";
        public string VoyageID = "";
        public string CompanyNameV = "";
        public string Remarks = "";
        public string BkgId = "0";
        public string EnqID = "0";
        public string Status = "";
        public string OfficeCode = "";
        public string CancelReasonID = "0";
        public string CancelReason = "";
        public string RejectReasonID = "0";
        public string RejectReason = "";
        public string ValidStatus = "";
        public int ValidStatusID;
        public string BkgDate = "";
        public string Reason = "";
        public string EnqCntrID = "0";
        public int OpenCount;
        public string TextValues = "";
        public string UserID = "";
        public string PageName = "";
        public string AttachName = "";
        public string AttachFile = "";
        public string AID = "";
        public int PaymentCenterID = 0;
        public int SlotUptoID = 0;

    }
}
